version: '3.7'
services:
  mysqldb:
        container_name: mysqldb
        restart: always
        image: mysql:8.0.31
        environment: 
            MYSQL_USER: admin
            MYSQL_PASSWORD: test
        ports: 
        -  "5432:5432"
  redis:
        container_name: redisdb
        image: redis:7.0.5-alpine


    

